# Generated by Django 3.2.7 on 2021-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='B_Numb',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='U_Agen',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
