# Generated by Django 3.2.7 on 2021-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211018_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='E_Mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='P_Word',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='D_Auth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='D_ChID',
            field=models.CharField(max_length=100),
        ),
    ]
