# Generated by Django 3.2.7 on 2021-10-30 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20211023_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='U_PreM',
        ),
        migrations.CreateModel(
            name='Pre_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_User', models.CharField(max_length=9)),
                ('U_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
