# Generated by Django 3.2.7 on 2021-11-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20211030_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_B_TO', models.CharField(max_length=100)),
                ('V_A_TO', models.CharField(max_length=100)),
                ('F_Date', models.DateTimeField(auto_now_add=True)),
                ('U_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
