# Generated by Django 3.2.7 on 2021-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_verifyme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='D_Auth',
            field=models.BinaryField(max_length=500, null=True),
        ),
    ]
