# Generated by Django 3.2.7 on 2021-11-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_userauthentication_d_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='E_Mail',
            field=models.BinaryField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='P_Word',
            field=models.BinaryField(max_length=100, null=True),
        ),
    ]
